server:
  port: 8080

spring:
  application:
    name: recommend-service
  datasource:
    url: ${RECOMMEND_DATASOURCE_URL}
    username: ${RECOMMEND_DATASOURCE_USERNAME}
    password: ${RECOMMEND_DATASOURCE_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always