apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommend-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommend-service
  template:
    metadata:
      labels:
        app: recommend-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: recommend-service
          image: financedoc.kr.ncr.ntruss.com/recommend-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: RECOMMEND_DATASOURCE_URL
              value: jdbc:postgresql://recommend-db.db.svc.cluster.local:5432/recommenddb
            - name: RECOMMEND_DATASOURCE_USERNAME
              value: user
            - name: RECOMMEND_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recommend-db-secret
                  key: RECOMMEND_DATASOURCE_PASSWORD
            - name: OPEN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: recommend-secret
                  key: OPEN_API_KEY
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"