apiVersion: v1
kind: Service
metadata:
  name: recommend-service-service
spec:
  selector:
    app: recommend-service
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30004
  type: NodePort